### ISSUE TITLE
Is it necessery to change  the Keras layer params names ?

### ISSUE THREAD

**Issue by said120276** [USCDataScience/dl4j-kerasimport-examples#2]
HI;
thanks for that work.
I found that in your data file :inception-model-weights.h5 . the Keras layer params names are of type : gamma,beta ,mean,std . But in DL4J "class KerasBatchNormalization" they use : gamma,beta ,running-mean,running-std ;
And when I change them manually in the class  the program work fine.

**Comment by thammegowda** [comment]
It had worked for me out of the box, without any change. 
Since it was tested on SNAPSHOT code, probably they (DL4J developers) might have updated the code in recent days.

**Comment by said120276** [comment]
I think so .I'm using ancient one.

**Comment by thammegowda** [comment]
Please send a Pull request with the changes you have made, I will have a look, Thanks :-)

**Comment by said120276** [comment]
I m  an amateur,'pull request' do you think its necessery ?
I used  those classes that I found here : https://github.com/deeplearning4j/deeplearning4j/tree/model_loading/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras
I changed two things  : 
1  Those strings in the class layers.KerasBatchNormalization  :
   public static final String PARAM_NAME_RUNNING_MEAN = "mean";(instead of running-mean).
    public static final String PARAM_NAME_RUNNING_STD = "std";(instead of running-std).
2  And I put the method " helperImportWeights(weightsArchive, weightsRoot)" in the constructor of the class KerasModel ,otherwise I get the error "weights ==null". so what do you think :)?

**Comment by thammegowda** [comment]
first, you are not an amateur since you're working with these stuff and also figured out how to get it fixed.

Second, thanks for sharing your changes in the previous comment. It is good enough for now.

**Comment by said120276** [comment]
Thanks, can you help me - if you have time - why I cant get it work using so called SNAPSHOT 3 ?
when I use :"  <dl4j.version>0.7.3-SNAPSHOT</dl4j.version> " in the POM I get error  : missing artifact.. .you said in your previous comment : "Since it was tested on SNAPSHOT code, probably they  .."what that mean?

**Comment by thammegowda** [comment]
@said120276 
I cleared my previous build and rebuild the SNAPSHOTs and tested again. It worked, no modifications required.

> "Since it was tested on SNAPSHOT code, probably they .."what that mean?

SNAPSHOT version is the jar built directly from the git repository of https://github.com/deeplearning4j/deeplearning4j. It means that the code can be modified each day. When a RELEASE is made, the jars will be uploaded to maven central repository and they remain unmodified. Ideally we/users should be waiting for release version, but I was too excited to not wait till that happens.

I see you are also very keen on trying it before the release. Hope this helps:

 [X] built and installed https://github.com/deeplearning4j/libnd4j/
 [X] built and installed https://github.com/bytedeco/javacpp
 [X] built and installed https://github.com/deeplearning4j/nd4j
 [X] built and installed https://github.com/deeplearning4j/DataVec
 [X] built and installed https://github.com/deeplearning4j/deeplearning4j

Most of the above are maven projects. you may find README or build instructions in each repository. Some of them are as easy as `mvn install -DskipTests`. 
Another trick I used to simplify build was to disable/exclude `cuda` modules. I just commented the `cuda` related maven sub modules to simplify my build (since cuda is optional for DL4J and I dont need it).

So, when deeplearning4j releases `0.7.3` to maven central, we dont need to build any of these above.

**Comment by said120276** [comment]
Thanks for your help it's very constructive; I'm going to rebuild it.
