### ISSUE TITLE
can not download the project

### ISSUE THREAD

**Issue by jasstionzyf** [USCDataScience/dl4j-kerasimport-examples#4]
when i fetch this project, get error:
error downloading object: dl4j-import-example/data/inception-model-weights.h5 (ecb4f17): Smudge error: Error downloading dl4j-import-example/data/inception-model-weights.h5 (ecb4f17f293e39de7336d04763023298036148a0aa6d47d6417dfbacddef1772): batch response: This repository is over its data quota. Purchase more data packs to restore access.

**Comment by chrismattmann** [comment]
cc @thammegowda

**Comment by thammegowda** [comment]
@jasstionzyf Thanks for reporting. We are working on this. 
Mean while you [can download the zip instead of cloning the repo](https://github.com/USCDataScience/dl4j-kerasimport-examples/archive/master.zip).
And replace the file at `dl4j-import-example/data/inception-model-weights.h5` with [the one at this link](https://raw.githubusercontent.com/USCDataScience/dl4j-kerasimport-examples/98ec48b56a5b8fb7d54a2994ce9cb23bfefac821/dl4j-import-example/data/inception-model-weights.h5)

@chrismattmann  I contacted github support. However, I have not heard back yet.  Have sent two messages so far (second one today).  If  I don't hear back by Monday then we need a plan B to host this repo.

**Comment by jasstionzyf** [comment]
@thammegowda  thanks for your reply very much.

**Comment by chrismattmann** [comment]
thanks @thammegowda got it.

**Comment by chrismattmann** [comment]
@thammegowda see: https://github.com/blog/1986-announcing-git-large-file-storage-lfs I think we may have gone beyond our monthly bandwidth quota...

**Comment by chrismattmann** [comment]
And see this @thammegowda https://github.com/streamlink/streamlink/issues/811#issuecomment-294939260

**Comment by chrismattmann** [comment]
please use work-around suggested by @thammegowda in https://github.com/USCDataScience/dl4j-kerasimport-examples/issues/4#issuecomment-299673691
